### PR TITLE
Corrects code syntax for #time-parse section

### PR DESCRIPTION
**Pull request by neilor**
Starting my Open Source Carreer with an little contribution.

### CODE REVIEW

**Comment by Brunozrk** [comment]
:+1: 

Should prefer single-quoted?

`Time.zone.parse('2015-03-02 19:05:37')`

**Comment by bbatsov** [comment]
Thanks for spotting this. @Brunozrk's remark is correct. We've been using single-quotes so far. Can you update the PR?

**Comment by neilor** [comment]
Thanks @Brunozrk!

I've updated PR.

**Comment by bbatsov** [comment]
@neilor Looks good. Just one tiny final detail - squash the two commits into one.

**Comment by neilor** [comment]
Squashed!

**Comment by bbatsov** [comment]
:+1: Thanks!

**Pull request merged**
